### ISSUE TITLE
No such layer: activation_49.

### ISSUE THREAD

**Issue by Arkaprabha1012** [lisssse14/Grad_CAM_PLUS_PLUS#1]
Hello,
The work is very neat and clean but I am getting some error while running your code for resnet50 pretrained imagenet model.
The last conv block of resnet50 is conv5_block3_out. but here You have mentioned activation_49. I have tried with conv5_block3_out but the output is varying in that case. In case of activation_49 I am getting an error like no such layer activation_49. Can you please help me with this issue?How I can actually use activation_49. How your code passed this ?

**Comment by Ecgbert** [comment]
I apologize for the late reply, as I am not currently working in deep learning, so I may not be able to answer you correctly.

The possible reasons are as follows

1. the model you are using may be different from mine, you can expand the architecture of the model to see what the correct output layer is
2. if activation_49 does not exist, you can try to use the last level of activation, which should be equivalent
3. it is possible that tensorflow or keras version is causing this problem

Hope this helps, have a nice day!
